project:
  output-dir: output
  preview: 
    port: 4200

linestretch: 1.3
format: 
  memo-pdf:
    branding: false # true oder false
    lang: de
  html:
    theme: cosmo
    css: styles.scss
    echo: false